# ===============================
# Dataset configuration
# ===============================
dataset:
  name: 
# ===============================
# Model configuration
# ===============================
model:
  name: "negbio"              # or "poisson"
  latent_dim: 128             # dimension of latent variable z
  reparam_type: "gamma"       # "gumbel" or "gamma"
  max_count: 30
  tau: 1.0
  kl: "analytical"                  # mc or analytical
  latent_act: "sigmoid"
# ===============================
# Encoder configuration
# ===============================
encoder:
  type: "conv"                # or "linear"
  input_dim:                # only needed for linear encoder
    MNIST: 784
    CIFAR16: 768
    Omniglot: 28
  latent_dim: 128
  use_norm: true
  bias: true
  activation_fn: "swish"         #{'swish', 'elu', 'relu', 'leaky_relu'}
  use_bn: false
  use_se: true
  res_eps: 1.0
  enc_norm: true
  enc_bias: true
# ===============================
# Decoder configuration
# ===============================
decoder:
  type: "conv"                # or "linear"
  output_dim: 784             # only needed for linear decoder
  latent_dim: 128
  out_channel:                 # only needed for conv decoder
    MNIST: 1
    CIFAR16: 3
    Omniglot: 1
  size:
    MNIST: 7
    CIFAR16: 4
    Omniglot: 7
# ===============================
# Optimizer configuration
# ===============================
optimizer:
  name: "adam"                # or "sgd"
  lr: 0.001                  # learning rate
  weight_decay: 0.0           # optional
# ===============================
# Trainer settings
# ===============================
trainer:
  beta_max: 5.0               # max beta for KL scheduling
  schedule_epochs: 250        # warm-up schedule for beta
  max_epochs: 100             # total training epochs
  gpus: 1                     # number of GPUs to use

# ===============================
# Logging / checkpointing (optional)
# ===============================

eval:
  fid_feature: 64
  log_images: true



logging:
  use_wandb: False
  wandb_project: "vae-experiments"
  log_images: true
  save_checkpoints: true
  monitor: "val_fid"